output_dir: '../../CustomContacts/Code/Generated/Swiftgen'
fonts:
  inputs: '../../CustomContacts/Resources'
  outputs:
    - templatePath: ../../Templates/SwiftGen/FontsTemplate.stencil
      output: Fonts+Constants.generated.swift
plist:
  inputs: '../../CustomContacts/Resources'
  outputs:
    - templatePath: ../../Templates/SwiftGen/PList.stencil
      output: PList.generated.swift
strings:
  inputs: '../../CustomContacts/Resources/Localization/en.lproj/Localizable.strings'
  outputs:
    - templatePath: ../../Templates/SwiftGen/LocalizableKeysTemplate.stencil
      output: LocalizableKeys+Constants.generated.swift
      params:
        enumName: Localizable
xcassets:
  inputs: '../../CustomContacts/Resources/Assets.xcassets'
  outputs:
    - templatePath: ../../Templates/SwiftGen/AssetsTemplate.stencil
      output: Assets+Constants.generated.swift
