output_dir: '../../FueledTemplate/Code/Generated/Swiftgen'
fonts:
  inputs: '../../FueledTemplate/Resources'
  outputs:
    - templatePath: ../../Templates/SwiftGen/FontsTemplate.stencil
      output: Fonts+Constants.generated.swift
json:
  inputs: '../../FueledTemplate/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json'
  outputs:
    - templatePath: ../../Templates/SwiftGen/JSON.stencil
      output: JSON.generated.swift
plist:
  inputs: '../../FueledTemplate/Resources'
  outputs:
    - templatePath: ../../Templates/SwiftGen/PList.stencil
      output: PList.generated.swift
strings:
  inputs: '../../FueledTemplate/Resources/Localization/en.lproj/Localizable.strings'
  outputs:
    - templatePath: ../../Templates/SwiftGen/LocalizableKeysTemplate.stencil
      output: LocalizableKeys+Constants.generated.swift
      params:
        enumName: Localizable
xcassets:
  inputs: '../../FueledTemplate/Resources/Assets.xcassets'
  outputs:
    - templatePath: ../../Templates/SwiftGen/AssetsTemplate.stencil
      output: Assets+Constants.generated.swift
